// Copyright (c) 2026 ObjectStack contributors. Apache-2.0 license.

import type * as Automation from '@objectstack/spec/automation';
type Flow = Automation.Flow;

/**
 * PR → PO conversion. When a PR is approved, draft a Purchase Order
 * pre-filled with the PR's commercial terms and link it back via
 * `source_request`. The PR is then flipped to `converted` so the same
 * PR can't be converted twice.
 *
 * The new PO lands as `draft` so the buyer can finalize line items
 * before sending. PO numbering is auto-generated by the PO hook (in your
 * fork) or left blank for the buyer to set.
 */
export const PRToPOConvertFlow: Flow = {
  name: 'procurement_request_to_po_convert',
  label: 'Convert Approved PR to Draft PO',
  description: 'On PR approval, auto-create a draft Purchase Order for the buyer.',
  type: 'record_change',

  variables: [{ name: 'prId', type: 'text', isInput: true, isOutput: false }],

  nodes: [
    {
      id: 'start',
      type: 'start',
      label: 'Start',
      config: {
        objectName: 'procurement_request',
        triggerType: 'record-after-update',
        condition: 'status == "approved" && converted_po == null',
      },
    },
    {
      id: 'get_pr',
      type: 'get_record',
      label: 'Load PR',
      config: {
        objectName: 'procurement_request',
        filter: { id: '{record.id}' },
        outputVariable: 'pr',
      },
    },
    {
      id: 'create_po',
      type: 'create_record',
      label: 'Create Draft PO',
      config: {
        objectName: 'procurement_order',
        fields: {
          po_number: 'PO-DRAFT-{pr.request_number}',
          vendor: '{pr.vendor}',
          source_request: '{pr.id}',
          status: 'draft',
          owner: '{pr.requester}',
          total_amount: '{pr.estimated_amount}',
          received_amount: 0,
          cost_center: '{pr.cost_center}',
          order_date: 'today()',
          expected_delivery: '{pr.needed_by}',
          notes:
            'Auto-generated from PR {pr.request_number} ({pr.title}). Review line items before sending.',
        },
        outputVariable: 'po',
      },
    },
    {
      id: 'link_back',
      type: 'update_record',
      label: 'Mark PR Converted',
      config: {
        objectName: 'procurement_request',
        filter: { id: '{record.id}' },
        fields: { status: 'converted', converted_po: '{po.id}' },
      },
    },
    {
      id: 'notify_buyer',
      type: 'notify',
      label: 'Notify Buyer',
      config: {
        recipients: ['{pr.requester}'],
        title: 'PO drafted: {pr.title}',
        body: 'A draft PO was created from your approved request "{pr.title}". Add line items and send to the vendor.',
        actionUrl: '/objects/procurement_order/{po.id}',
      },
    },
    { id: 'end', type: 'end', label: 'End' },
  ],

  edges: [
    { id: 'e1', source: 'start', target: 'get_pr', type: 'default' },
    { id: 'e2', source: 'get_pr', target: 'create_po', type: 'default' },
    { id: 'e3', source: 'create_po', target: 'link_back', type: 'default' },
    { id: 'e4', source: 'link_back', target: 'notify_buyer', type: 'default' },
    { id: 'e5', source: 'notify_buyer', target: 'end', type: 'default' },
  ],
};
